import {
    // create naive ui
    create,
    // component
    NButton,
    NButtonGroup,
    NForm,
    NInput,
    NCheckbox,
    NIcon,
    NDivider,
    NFormItem,
    NLayout,
    NLayoutContent,
    NLayoutHeader,
    NLayoutSider,
    NLayoutFooter,
    NMenu,
    NDialog,
    NTooltip,
    NTree,
    NDataTable,
    NGrid,
    NGridItem,
    NSpace,
    NPagination,
    NCard,
    NTag,
    NProgress,
    NTabs,
    NTabPane,
    NAvatar,
    NList,
    NListItem,
    NTime,
    NImage
} from 'naive-ui'
export const naive = create({
    components: [NButton, NForm, NInput, NCheckbox, NIcon, NDivider, NFormItem, NLayout,
        NLayoutContent,
        NLayoutHeader,
        NLayoutSider,
        NLayoutFooter,
        NMenu,
        NDialog,
        NTooltip,
        NTree,
        NDataTable,
        NButtonGroup,
        NGrid,
        NGridItem,
        NSpace,
        NPagination,
        NCard,
        NTag,
        NProgress,
        NTabs,
        NTabPane,
        NAvatar,
        NList,
    NListItem,
    NTime,
    NImage
    ]
});
