name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install cnpm -g --registry=https://registry.npmmirror.com
    - run: cnpm i yarn
    - run: yarn install
    - run: yarn run build 

    - name: Deploy # 将打包内容发布到 github page
      uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
      with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.VITE_PING_ADMIN }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
          BRANCH: master
          FOLDER: dist
          REPOSITORY_NAME: Gitpingping/Gitpingping.github.io # 这是我的 github page 仓库
          TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下
