name: 构建部署
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4  
        with:
          persist-credentials: false
      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install cnpm -g --registry=https://registry.npm.taobao.org
          cnpm install yarn
          yarn install
          install run build
      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@4.1.5 # 使用别人写好的 actions
        with:  # 自定义环境变量
          token: ${{ secrets.VITE_PING_ADMIN }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
          folder: dist
          branch: main
          repository-name: Gitpingping/Gitpingping.github.io # 这是我的 github page 仓库

